@startuml Container_Diagram_Full_Infrastructure
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(passenger, "Пассажир", "Заказывает поездки")
Person(driver, "Водитель", "Принимает заказы и получает выплаты")
Person(manager, "Корпоративный менеджер", "Управляет счетами")
Person(accountant, "Бухгалтер", "Контролирует выплаты")
Person(sre_engineer, "SRE инженер", "Мониторит и поддерживает систему")

AddElementTag("ms", $borderColor="black", $fontColor="black")
AddRelTag("ms", $textColor="black", $lineColor="black")
AddRelTag("msa", $textColor="black", $lineColor="black", $lineStyle=DashedLine())

System_Boundary(go_future_system, "GoFuture Platform") {
    System_Boundary(mobile, "Mobile apps") {
        Container(web_passenger, "Пассажирское приложение", "iOS/Android/Huawei", "Интерфейс для пассажиров")
        Container(web_driver, "Водительское приложение", "iOS/Android/Huawei", "Интерфейс для водителей")
    }
    System_Boundary(cluster, Kubernetes Cluster, $tags="ms"){
        System_Boundary(web, "Web apps") {
            Container(web_portal, "Корпоративный веб-портал", "Web Application, pod", "Управление заказами")
            Container(admin_portal, "Админ-панель", "Web Application, pod", "Управление выплатами")
        }
        Container(api_gateway, API gateway, Envoy Gateway, $tags="ms")
        System_Boundary(driver_domain, Driver Domain){
            Container(bff_driver, BFF Service (driver), "?", $tags="ms")
            ContainerDb(bff_driver_cache, In Memory Cache (driver), "?", $tags="ms")
            Rel_R(bff_driver, bff_driver_cache, cache data,  $tags="ms")                
        }
        System_Boundary(passenger_domain, Passenger Domain){
            Container(bff_passenger, BFF Service (passenger), "?", $tags="ms")
            ContainerDb(bff_passenger_cache, In Memory Cache (passenger), "?", $tags="ms")
            Rel_R(bff_passenger, bff_passenger_cache, cache data,  $tags="ms")                
        }
        System_Boundary(payouts_domain, Payouts Domain){
            Container(bff_admin, BFF Service (admin), "?", $tags="ms")
            ContainerDb(bff_admin_cache, In Memory Cache (admin), "?", $tags="ms")
            Rel_R(bff_admin, bff_admin_cache, cache data,  $tags="ms")                
        }
        System_Boundary(corporate_domain, Corporate Domain){
            Container(bff_portal, BFF Service (portal), "?", $tags="ms")
            ContainerDb(bff_portal_cache, In Memory Cache (portal), "?", $tags="ms")
           Rel_R(bff_portal, bff_portal_cache, cache data,  $tags="ms")                
        }
       
        Rel(web_passenger, api_gateway, HTTP/REST API, $tags="ms")
        Rel(web_driver, api_gateway, HTTP/REST API, $tags="ms")
        Rel(web_portal, api_gateway, HTTP/REST API, $tags="ms")
        Rel(admin_portal, api_gateway, HTTP/REST API, $tags="ms")
        Rel(api_gateway, bff_passenger, routes traffic to, $tags="ms")
        Rel(api_gateway, bff_driver, routes traffic to, $tags="ms")
        Rel(api_gateway, bff_portal, routes traffic to, $tags="ms")
        Rel(api_gateway, bff_admin, routes traffic to, $tags="ms")
     
            
        System_Boundary(ci_cd, "CI/CD"){
            Person(dev_engineer, "Разработчик", "Разрабатывает новые функции")
            Container(jenkins, "Jenkins", "CI/CD pod on Kubernetes", "Сборка и деплой сервисов", $tags="ms")
            System_Ext(artifact_repo, "Artifact Repository", "Dcoker registry", "Хранение образов приложения", $tags="ms")
            Container(ci_worker, "CI/CD Workers", "Pods", "Выполнение задач сборки и тестов", $tags="ms")
            Rel(jenkins, ci_worker, "Запускает задачи", "SSH/API")
            Rel_L(ci_worker, artifact_repo, "Пушит образы", "Docker Push")
            Rel(jenkins, artifact_repo, "Деплоит образы", "Docker Pull")
            Rel_D(dev_engineer, jenkins, "Запускает сборки")
        }
    }
    
    ' ### ОСНОВНОЙ МОНОЛИТ ###
    Container(app_monolith, "GoFuture Monolith", "Django Application", "Содержит всю бизнес-логику")
    Rel(api_gateway, app_monolith, routes traffic to, $tags="ms")
    Rel(bff_passenger, app_monolith, uses,  $tags="ms")
    Rel(bff_driver, app_monolith, uses,  $tags="ms")
    Rel(bff_portal, app_monolith, uses,  $tags="ms")
    Rel(bff_admin, app_monolith, uses,  $tags="ms")
    
    ' ### БАЗЫ ДАННЫХ ###
    ContainerDb(db_main, "Основная БД", "PostgreSQL RDS", "Хранит все бизнес-данные")
    ContainerDb(db_cache, "In-memory кеш", "Redis", "Кеширование данных")
    ContainerDb(db_search, "Поисковый индекс", "Elasticsearch", "Геопоиск водителей")
    
    ' ### ОЧЕРЕДИ И ВОРКЕРЫ ###
    ContainerQueue(mq_broker, "Брокер сообщений", "RabbitMQ", "Очередь для фоновых задач")
    Container(app_worker, "Воркеры фоновых задач", "Celery", "Обработка асинхронных задач")
    
    ' ### МОНИТОРИНГ И OBSERVABILITY ###
    Container(monitoring, "Prometheus", "Monitoring System", "Сбор метрик и мониторинг")
    Container(grafana, "Grafana", "Dashboard System", "Визуализация метрик и дашборды")
    Container(loki, "Loki", "Log Aggregation", "Сбор и анализ логов")
    Container(alert_manager, "Alertmanager", "Alert System", "Управление алертами")
    

    ' ### АНАЛИТИЧЕСКАЯ ИНФРАСТРУКТУРА ###
    Container(analytics_engine, "Analytics Engine", "Spark/Flink", "Обработка аналитических данных")
    Container(analytics_db, "Analytics DB", "ClickHouse", "Хранение аналитических данных")
    Container(datalens, "DataLens", "BI Tool", "Визуализация бизнес-метрик")
}

' ### ВНЕШНИЕ СИСТЕМЫ ###
System_Ext(yandex_pay, "Яндекс Пэй", "Платёжный шлюз")
System_Ext(yandex_maps, "Яндекс Карты", "Картографический сервис")
System_Ext(fcm, "FCM", "Push-сервис Google")
System_Ext(apns, "APNs", "Push-сервис Apple")
System_Ext(huawei_push, "Huawei Push Kit", "Push-сервис Huawei")
System_Ext(bank_api, "API Банка", "Банковские выплаты")

' ### СВЯЗИ ПОЛЬЗОВАТЕЛЕЙ ###
Rel(passenger, web_passenger, "Использует")
Rel(driver, web_driver, "Использует")
Rel(manager, web_portal, "Использует")
Rel(accountant, admin_portal, "Использует")

Rel(sre_engineer, grafana, "Мониторит систему")
Rel(sre_engineer, alert_manager, "Настраивает алерты")

Rel(app_monolith, db_main, "Чтение/запись (ORM)")
Rel(app_monolith, db_cache, "Кеширование данных")
Rel(app_monolith, db_search, "Геопоиск водителей")
Rel(app_monolith, mq_broker, "Отправка задач")

Rel(app_monolith, yandex_pay, "Обработка платежей")
Rel(app_monolith, yandex_maps, "Запросы геоданных")
Rel(app_monolith, bank_api, "Инициирование выплат")

' ### ASYNC WORKERS ###
Rel(app_worker, mq_broker, "Получает задачи из", "AMQP")
Rel(app_worker, db_main, "Чтение/запись данных", "ORM")
Rel(app_worker, db_main, "Сохраняет результаты", "ORM")
Rel(app_worker, fcm, "Отправляет уведомления", "REST API")
Rel(app_worker, apns, "Отправляет уведомления", "REST API")
Rel(app_worker, huawei_push, "Отправляет уведомления", "REST API")
Rel(app_worker, bank_api, "Выполняет выплаты", "REST API")

' ### МОНИТОРИНГ ###
Rel(app_monolith, monitoring, "Отправляет метрики", "Prometheus Metrics")
Rel(app_worker, monitoring, "Отправляет метрики", "Prometheus Metrics")
Rel(db_main, monitoring, "Метрики БД", "PostgreSQL Exporter")
Rel(mq_broker, monitoring, "Метрики очередей", "RabbitMQ Exporter")

Rel(monitoring, grafana, "Предоставляет данные", "PromQL")
Rel(monitoring, alert_manager, "Отправляет алерты", "Alert Rules")
Rel(alert_manager, sre_engineer, "Отправляет уведомления", "Email/Slack/Pager")

Rel(app_monolith, loki, "Отправляет логи", "Loki Logs")
Rel(app_worker, loki, "Отправляет логи", "Loki Logs")

' ### АНАЛИТИКА ###
Rel(app_monolith, analytics_engine, "Отправляет события", "AMQP")
Rel(app_worker, analytics_engine, "Отправляет события", "AMQP")
Rel(analytics_engine, analytics_db, "Записывает данные", "ETL Process")
Rel(analytics_db,datalens, "Предоставляет данные", "SQL Queries")
Rel(datalens, manager, "Бизнес-отчёты", "Dashboards")
Rel(datalens, accountant, "Финансовые отчёты", "Dashboards")

@enduml